import type { IngredientInput } from "@/store/ingredients";

/**
 * The catering business's full ingredient catalog, one-time seeded into the
 * ingredients store on first run. Each row: English name, Tamil name, tag,
 * unit, and reference price. `qty`/`openingStock`/`lowStockThreshold` stay 0
 * unless the user sets them.
 */
export const INGREDIENT_CATALOG: IngredientInput[] = [
  { name: "3 Burner Gas Stove", tamilName: "3 பர்னர் கேஸ் அடுப்பு", tag: "vessel", unit: "piece", qty: 0, globalPrice: 650, openingStock: 0, lowStockThreshold: 0 },
  { name: "Ada", tamilName: "அடை", tag: "grocery", unit: "kg", qty: 0, globalPrice: 100, openingStock: 0, lowStockThreshold: 0 },
  { name: "Apple Ponni Rice", tamilName: "ஆப்பிள் பொன்னி அரிசி", tag: "grocery", unit: "kg", qty: 0, globalPrice: 68, openingStock: 0, lowStockThreshold: 0 },
  { name: "Asafoetida", tamilName: "எல் ஜி காயம்", tag: "grocery", unit: "kg", qty: 0, globalPrice: 1500, openingStock: 0, lowStockThreshold: 0 },
  { name: "Asafoetida Powder", tamilName: "LGகாயம்பொடி", tag: "grocery", unit: "kg", qty: 0, globalPrice: 1100, openingStock: 0, lowStockThreshold: 0 },
  { name: "Aval", tamilName: "அவல்", tag: "grocery", unit: "kg", qty: 0, globalPrice: 80, openingStock: 0, lowStockThreshold: 0 },
  { name: "Banana Fruit", tamilName: "வாழைப் பழம்", tag: "vegetables", unit: "piece", qty: 0, globalPrice: 10, openingStock: 0, lowStockThreshold: 0 },
  { name: "Banana Leaf", tamilName: "வாழ இலை", tag: "vegetables", unit: "piece", qty: 0, globalPrice: 5, openingStock: 0, lowStockThreshold: 0 },
  { name: "Basin", tamilName: "பேசன்", tag: "vessel", unit: "piece", qty: 0, globalPrice: 20, openingStock: 0, lowStockThreshold: 0 },
  { name: "Beans", tamilName: "பீன்ஸ்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 100, openingStock: 0, lowStockThreshold: 0 },
  { name: "Beetroot", tamilName: "பீட்ரூட்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 60, openingStock: 0, lowStockThreshold: 0 },
  { name: "Big Onion", tamilName: "பல்லரி", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 50, openingStock: 0, lowStockThreshold: 0 },
  { name: "Bitter Gourd", tamilName: "பாவக்காய்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 80, openingStock: 0, lowStockThreshold: 0 },
  { name: "Brinjal", tamilName: "கத்திரிக்காய்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 60, openingStock: 0, lowStockThreshold: 0 },
  { name: "Broad Beans", tamilName: "அவரக்காய்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 60, openingStock: 0, lowStockThreshold: 0 },
  { name: "Brt Coconut Oil", tamilName: "BRT தேங்காய் எண்ணை", tag: "grocery", unit: "litre", qty: 0, globalPrice: 300, openingStock: 0, lowStockThreshold: 0 },
  { name: "Cabbage", tamilName: "முட்டைகோஸ்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 70, openingStock: 0, lowStockThreshold: 0 },
  { name: "Candy Sugar", tamilName: "சீனி", tag: "grocery", unit: "kg", qty: 0, globalPrice: 90, openingStock: 0, lowStockThreshold: 0 },
  { name: "Canister", tamilName: "கான்பினார்", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Capsicum", tamilName: "கேப்சிகம்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 100, openingStock: 0, lowStockThreshold: 0 },
  { name: "Cardamom", tamilName: "ஏலக்காய்", tag: "masala-spices", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Cauliflower", tamilName: "காலிபிளவர்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 80, openingStock: 0, lowStockThreshold: 0 },
  { name: "Chair", tamilName: "செயர்", tag: "vessel", unit: "piece", qty: 0, globalPrice: 10, openingStock: 0, lowStockThreshold: 0 },
  { name: "Chakku", tamilName: "சக்கு", tag: "grocery", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Chicken Masala", tamilName: "சிக்கன் மசாலா", tag: "masala-spices", unit: "kg", qty: 0, globalPrice: 480, openingStock: 0, lowStockThreshold: 0 },
  { name: "Chickpea Dal", tamilName: "கடலை பருப்பு", tag: "grocery", unit: "kg", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Chuku", tamilName: "சுக்கு", tag: "grocery", unit: "gm", qty: 0, globalPrice: 50, openingStock: 0, lowStockThreshold: 0 },
  { name: "Cinnamon", tamilName: "பட்டை", tag: "grocery", unit: "kg", qty: 0, globalPrice: 1500, openingStock: 0, lowStockThreshold: 0 },
  { name: "Cloves", tamilName: "கிராம்பு", tag: "grocery", unit: "kg", qty: 0, globalPrice: 800, openingStock: 0, lowStockThreshold: 0 },
  { name: "Coconut", tamilName: "தேங்காய்", tag: "grocery", unit: "piece", qty: 0, globalPrice: 45, openingStock: 0, lowStockThreshold: 0 },
  { name: "Colocasia", tamilName: "சேம்பு கிழங்கு", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 120, openingStock: 0, lowStockThreshold: 0 },
  { name: "Coriander Leaves", tamilName: "மல்லி இலை", tag: "grocery", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Coriander Powder", tamilName: "மல்லி பொடி", tag: "masala-spices", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Cucumber", tamilName: "வெள்ளரிக்காய்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 50, openingStock: 0, lowStockThreshold: 0 },
  { name: "Cumin", tamilName: "ஜீரகம்", tag: "grocery", unit: "kg", qty: 0, globalPrice: 360, openingStock: 0, lowStockThreshold: 0 },
  { name: "Curry Leaves", tamilName: "கறிவேப்பிலை", tag: "grocery", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Cylinder", tamilName: "சிலிண்டர்", tag: "vessel", unit: "kg", qty: 0, globalPrice: 130, openingStock: 0, lowStockThreshold: 0 },
  { name: "Drum", tamilName: "டிரம்", tag: "vessel", unit: "piece", qty: 0, globalPrice: 50, openingStock: 0, lowStockThreshold: 0 },
  { name: "Drumstick", tamilName: "முருங்கைக்காய்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 80, openingStock: 0, lowStockThreshold: 0 },
  { name: "Fenugreek", tamilName: "வெந்தயம்", tag: "masala-spices", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Firewood", tamilName: "விரகு", tag: "grocery", unit: "kg", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Fish Maker", tamilName: "மீன்மேக்கர்", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Garlic", tamilName: "பூண்டு", tag: "grocery", unit: "kg", qty: 0, globalPrice: 200, openingStock: 0, lowStockThreshold: 0 },
  { name: "Ginger", tamilName: "இஞ்சி", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 200, openingStock: 0, lowStockThreshold: 0 },
  { name: "Gooseberry", tamilName: "நெல்லிக்காய்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 120, openingStock: 0, lowStockThreshold: 0 },
  { name: "Green Peas", tamilName: "பச்சை பட்டாணி", tag: "grocery", unit: "kg", qty: 0, globalPrice: 100, openingStock: 0, lowStockThreshold: 0 },
  { name: "Green Pepper (pandi)", tamilName: "பச்சை மிளகு (பாண்டி)", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 80, openingStock: 0, lowStockThreshold: 0 },
  { name: "Grinder", tamilName: "கிரெண்டர்", tag: "vessel", unit: "piece", qty: 0, globalPrice: 600, openingStock: 0, lowStockThreshold: 0 },
  { name: "Ice Cream", tamilName: "ஐஸ்கிரீம்", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Idli Kuttuvam", tamilName: "இட்லி குட்டுவம்", tag: "vessel", unit: "piece", qty: 0, globalPrice: 250, openingStock: 0, lowStockThreshold: 0 },
  { name: "Juck", tamilName: "ஜெக்", tag: "vessel", unit: "piece", qty: 0, globalPrice: 20, openingStock: 0, lowStockThreshold: 0 },
  { name: "Kadavam", tamilName: "கடவம்", tag: "vessel", unit: "piece", qty: 0, globalPrice: 250, openingStock: 0, lowStockThreshold: 0 },
  { name: "Kannappai", tamilName: "கண்ணாப்பை", tag: "vessel", unit: "piece", qty: 0, globalPrice: 50, openingStock: 0, lowStockThreshold: 0 },
  { name: "Karandi", tamilName: "கரண்டி", tag: "vessel", unit: "piece", qty: 0, globalPrice: 10, openingStock: 0, lowStockThreshold: 0 },
  { name: "Karungaali Powder", tamilName: "கருங்காலி பொடி", tag: "masala-spices", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Kashmiri Chilli Powder", tamilName: "காஷ்மீரி சில்லி பொடி", tag: "grocery", unit: "kg", qty: 0, globalPrice: 300, openingStock: 0, lowStockThreshold: 0 },
  { name: "Kayam", tamilName: "காயம்", tag: "grocery", unit: "kg", qty: 0, globalPrice: 1500, openingStock: 0, lowStockThreshold: 0 },
  { name: "Kerosene", tamilName: "மண் எண்ணை", tag: "grocery", unit: "litre", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Kundhuponi", tamilName: "குந்துபோணி", tag: "vessel", unit: "piece", qty: 0, globalPrice: 25, openingStock: 0, lowStockThreshold: 0 },
  { name: "Kutai", tamilName: "குட்டை", tag: "vessel", unit: "piece", qty: 0, globalPrice: 150, openingStock: 0, lowStockThreshold: 0 },
  { name: "Ladies Finger", tamilName: "வெண்டைக்காய்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 50, openingStock: 0, lowStockThreshold: 0 },
  { name: "Ladle", tamilName: "அகப்பை", tag: "vessel", unit: "piece", qty: 0, globalPrice: 30, openingStock: 0, lowStockThreshold: 0 },
  { name: "Large Cast Vessel", tamilName: "பெரிய வார்ப்பு", tag: "vessel", unit: "piece", qty: 0, globalPrice: 350, openingStock: 0, lowStockThreshold: 0 },
  { name: "Large Uruli", tamilName: "பெரிய உருளி", tag: "vessel", unit: "piece", qty: 0, globalPrice: 150, openingStock: 0, lowStockThreshold: 0 },
  { name: "Lemon", tamilName: "எலுமிச்சை", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Matchbox", tamilName: "தீப்பெட்டி", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Matti Fruit", tamilName: "மட்டி பழம்", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Meat", tamilName: "கறி", tag: "grocery", unit: "kg", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Medium Cast Vessel", tamilName: "மீடியம் வார்ப்பு", tag: "vessel", unit: "piece", qty: 0, globalPrice: 250, openingStock: 0, lowStockThreshold: 0 },
  { name: "Milk Maid", tamilName: "மிலக் மேய்டு", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Milk Mavu", tamilName: "மில்க் மாவு", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Milk Powder (Everyday)", tamilName: "பால்பொடி (Everyday)", tag: "grocery", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Mint Leaves", tamilName: "புதினா இலை", tag: "grocery", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Mixie", tamilName: "மிக்ஸி", tag: "vessel", unit: "piece", qty: 0, globalPrice: 500, openingStock: 0, lowStockThreshold: 0 },
  { name: "Muthiri Fruit", tamilName: "முத்திரி பழம்", tag: "grocery", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Mutton Masala", tamilName: "மட்டன் மசாலா", tag: "masala-spices", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Narangai", tamilName: "நாரங்காய்", tag: "vegetables", unit: "piece", qty: 0, globalPrice: 100, openingStock: 0, lowStockThreshold: 0 },
  { name: "Nilavaka", tamilName: "நிலவாகா", tag: "vessel", unit: "piece", qty: 0, globalPrice: 50, openingStock: 0, lowStockThreshold: 0 },
  { name: "Palai", tamilName: "பாளை", tag: "vessel", unit: "piece", qty: 0, globalPrice: 35, openingStock: 0, lowStockThreshold: 0 },
  { name: "Pama Oil", tamilName: "பாமா ஆயில்", tag: "grocery", unit: "litre", qty: 0, globalPrice: 140, openingStock: 0, lowStockThreshold: 0 },
  { name: "Pame Oil", tamilName: "பமே ஆயில்", tag: "grocery", unit: "litre", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Pandan Leaf", tamilName: "ராம்பா இலை", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Papad", tamilName: "பப்படம்", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Parambu", tamilName: "பரம்பு", tag: "vessel", unit: "piece", qty: 0, globalPrice: 150, openingStock: 0, lowStockThreshold: 0 },
  { name: "Parotta Gas Stove", tamilName: "புரோட்டா கேஸ் அடுப்பு", tag: "vessel", unit: "piece", qty: 0, globalPrice: 1000, openingStock: 0, lowStockThreshold: 0 },
  { name: "Parotta Table", tamilName: "புரோட்டா மேஜை", tag: "vessel", unit: "piece", qty: 0, globalPrice: 500, openingStock: 0, lowStockThreshold: 0 },
  { name: "Perinjeeragam", tamilName: "பெரிஞ்சீரகம்", tag: "masala-spices", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Perinjeeragam Powder", tamilName: "பெரிஞ்சீரக பொடி", tag: "masala-spices", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Pineapple", tamilName: "பைனாப்பிள்", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Pineapple Color", tamilName: "அன்னாசி பழுப்பு", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Pineapple Essence", tamilName: "பையனாப்பின் எசன்ஸ்", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Plantain", tamilName: "வாழைக்காய்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 80, openingStock: 0, lowStockThreshold: 0 },
  { name: "Pomegranate", tamilName: "மாதுளம் பழம்", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Potato", tamilName: "உருளை கிழங்கு", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 50, openingStock: 0, lowStockThreshold: 0 },
  { name: "Raw Banana", tamilName: "ஏத்தன்காய்", tag: "vegetables", unit: "piece", qty: 0, globalPrice: 10, openingStock: 0, lowStockThreshold: 0 },
  { name: "Raw Mango", tamilName: "மாங்காய்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 100, openingStock: 0, lowStockThreshold: 0 },
  { name: "Rice (IVN)", tamilName: "அரிசி (IVN C.O)", tag: "grocery", unit: "kg", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Rice Box", tamilName: "அரி பெட்டி", tag: "vessel", unit: "piece", qty: 0, globalPrice: 75, openingStock: 0, lowStockThreshold: 0 },
  { name: "Rkg Ghee", tamilName: "RKG தெய்", tag: "grocery", unit: "kg", qty: 0, globalPrice: 800, openingStock: 0, lowStockThreshold: 0 },
  { name: "Round yam", tamilName: "சேணை கிழங்கு", tag: "grocery", unit: "kg", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Sabina Powder", tamilName: "சபீனா பொடி", tag: "masala-spices", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Sago", tamilName: "சவ்வரிசி", tag: "grocery", unit: "kg", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Salad Cucumber", tamilName: "சலாடு வெள்ளரி", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 100, openingStock: 0, lowStockThreshold: 0 },
  { name: "Salt Granules", tamilName: "உப்பு பரல்", tag: "masala-spices", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Salt Powder", tamilName: "உப்பு பொடி", tag: "masala-spices", unit: "kg", qty: 0, globalPrice: 13, openingStock: 0, lowStockThreshold: 0 },
  { name: "Sambar Dal", tamilName: "சாம்பார் பருப்பு", tag: "grocery", unit: "kg", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Sambar Pepper", tamilName: "சாம்பார் மிளகு", tag: "masala-spices", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Sambar Powder (Baby)", tamilName: "சாம்பார்பொடி (பேபி)", tag: "masala-spices", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Sattuvanam", tamilName: "சட்டுவம்", tag: "vessel", unit: "piece", qty: 0, globalPrice: 50, openingStock: 0, lowStockThreshold: 0 },
  { name: "Sesame Oil", tamilName: "நல்லெண்ணை", tag: "grocery", unit: "litre", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Single Burner Gas Stove", tamilName: "சிங்கிள் பர்னர் கேஸ் அடுப்பு", tag: "vessel", unit: "piece", qty: 0, globalPrice: 250, openingStock: 0, lowStockThreshold: 0 },
  { name: "Sippil", tamilName: "சிப்பில்", tag: "vessel", unit: "piece", qty: 0, globalPrice: 20, openingStock: 0, lowStockThreshold: 0 },
  { name: "Small Dal", tamilName: "சிறு பருப்பு", tag: "grocery", unit: "kg", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Small Karandi", tamilName: "சின்ன கரண்டி", tag: "vessel", unit: "piece", qty: 0, globalPrice: 10, openingStock: 0, lowStockThreshold: 0 },
  { name: "Small Onion", tamilName: "சின்ன உள்ளி", tag: "grocery", unit: "kg", qty: 0, globalPrice: 80, openingStock: 0, lowStockThreshold: 0 },
  { name: "Small Sattuvanam", tamilName: "சிறிய சட்டுவம்", tag: "vessel", unit: "piece", qty: 0, globalPrice: 40, openingStock: 0, lowStockThreshold: 0 },
  { name: "Small Uruli", tamilName: "சின்ன உருளி", tag: "vessel", unit: "piece", qty: 0, globalPrice: 150, openingStock: 0, lowStockThreshold: 0 },
  { name: "Snake Gourd", tamilName: "புடலங்காய்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 65, openingStock: 0, lowStockThreshold: 0 },
  { name: "Sugar", tamilName: "சர்க்கரை", tag: "grocery", unit: "kg", qty: 0, globalPrice: 120, openingStock: 0, lowStockThreshold: 0 },
  { name: "Sundu", tamilName: "சுண்டு", tag: "grocery", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Table", tamilName: "மேசை", tag: "vessel", unit: "piece", qty: 0, globalPrice: 30, openingStock: 0, lowStockThreshold: 0 },
  { name: "Tamarind", tamilName: "புளி", tag: "grocery", unit: "kg", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Tea Leaves", tamilName: "தேயிலை", tag: "grocery", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Thadiyangai", tamilName: "தடியங்காய்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 60, openingStock: 0, lowStockThreshold: 0 },
  { name: "Thaththolal", tamilName: "தத்தோலால்", tag: "grocery", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Tomato", tamilName: "தக்காளி", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 40, openingStock: 0, lowStockThreshold: 0 },
  { name: "Tomato peast", tamilName: "டொமட்டோ பேஸ்ட்", tag: "grocery", unit: "ml", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Towel", tamilName: "டவ்வல்", tag: "vessel", unit: "piece", qty: 0, globalPrice: 40, openingStock: 0, lowStockThreshold: 0 },
  { name: "Tray", tamilName: "டிரே", tag: "vessel", unit: "piece", qty: 0, globalPrice: 20, openingStock: 0, lowStockThreshold: 0 },
  { name: "Turmeric Powder", tamilName: "மஞ்சள் பொடி", tag: "masala-spices", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Urad Dal", tamilName: "உருட்டு உழுந்து", tag: "grocery", unit: "kg", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "VVD Oil", tamilName: "V.V.D. என்னை", tag: "grocery", unit: "litre", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Vaalie", tamilName: "வாழி", tag: "vessel", unit: "piece", qty: 0, globalPrice: 30, openingStock: 0, lowStockThreshold: 0 },
  { name: "Vanilla Essence", tamilName: "வெண்ணிலா எசன்ஸ்", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Vathal", tamilName: "வத்தல்", tag: "grocery", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Vathal Powder", tamilName: "வத்தல் பொடி", tag: "masala-spices", unit: "gm", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Vattai 10 Kg", tamilName: "வட்டை 10 கிலோ", tag: "vessel", unit: "piece", qty: 0, globalPrice: 100, openingStock: 0, lowStockThreshold: 0 },
  { name: "Vattai 15 Kg", tamilName: "வட்டை 15 கிலோ", tag: "vessel", unit: "piece", qty: 0, globalPrice: 100, openingStock: 0, lowStockThreshold: 0 },
  { name: "Vattai 20 Kg", tamilName: "வட்டை 20 கிலோ", tag: "vessel", unit: "piece", qty: 0, globalPrice: 100, openingStock: 0, lowStockThreshold: 0 },
  { name: "Vattai 30 Kg", tamilName: "வட்டை 30 கிலோ", tag: "vessel", unit: "piece", qty: 0, globalPrice: 120, openingStock: 0, lowStockThreshold: 0 },
  { name: "Vattai 40 Kg", tamilName: "வட்டை 40 கிலோ", tag: "vessel", unit: "piece", qty: 0, globalPrice: 150, openingStock: 0, lowStockThreshold: 0 },
  { name: "Vattai 50 Kg", tamilName: "வட்டை 50 கிலோ", tag: "vessel", unit: "piece", qty: 0, globalPrice: 150, openingStock: 0, lowStockThreshold: 0 },
  { name: "Vazhudhana", tamilName: "வழுதனங்காய்", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 60, openingStock: 0, lowStockThreshold: 0 },
  { name: "Vermicelli", tamilName: "சேமியா", tag: "grocery", unit: "kg", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Viccappa Kuttuvam", tamilName: "வீச்சப்ப குட்டுவம்", tag: "vessel", unit: "piece", qty: 0, globalPrice: 500, openingStock: 0, lowStockThreshold: 0 },
  { name: "Water Bottle", tamilName: "தண்ணீர் பாட்டில்", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Water Cup", tamilName: "தண்ணீர் கப்", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "White Cloth", tamilName: "வெள்ளை முண்டு", tag: "vessel", unit: "piece", qty: 0, globalPrice: 100, openingStock: 0, lowStockThreshold: 0 },
  { name: "Yam", tamilName: "சேனைகிழங்கு", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 60, openingStock: 0, lowStockThreshold: 0 },
  { name: "Ash Pumkin", tamilName: "தடியங்காய்", tag: "grocery", unit: "kg", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Beef", tamilName: "பீபி", tag: "meat-fish", unit: "kg", qty: 0, globalPrice: 500, openingStock: 0, lowStockThreshold: 0 },
  { name: "Carrot", tamilName: "கேரட்", tag: "vegetables", unit: "gm", qty: 0, globalPrice: 100, openingStock: 0, lowStockThreshold: 0 },
  { name: "Cashew Nut", tamilName: "அண்டி பருப்பு", tag: "grocery", unit: "kg", qty: 0, globalPrice: 1000, openingStock: 0, lowStockThreshold: 0 },
  { name: "Chicken", tamilName: "சிக்கன்", tag: "meat-fish", unit: "kg", qty: 0, globalPrice: 160, openingStock: 0, lowStockThreshold: 0 },
  { name: "Chilly Peast", tamilName: "சில்லி பேஸ்ட்", tag: "grocery", unit: "ml", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Curd", tamilName: "தயிர்", tag: "grocery", unit: "litre", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Egg", tamilName: "முட்டை", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Fish", tamilName: "பிஷ்", tag: "meat-fish", unit: "piece", qty: 0, globalPrice: 40, openingStock: 0, lowStockThreshold: 0 },
  { name: "Gas", tamilName: "காஸ்", tag: "fuel", unit: "kg", qty: 0, globalPrice: 175, openingStock: 0, lowStockThreshold: 0 },
  { name: "Gas Silinder", tamilName: "காஸ் சிலிண்டர்", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Green Chilly", tamilName: "கிறீன் சில்லி", tag: "grocery", unit: "kg", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "India Gate White Sella", tamilName: "இந்தியா கேட் வைட் செல்ல", tag: "grocery", unit: "kg", qty: 0, globalPrice: 135, openingStock: 0, lowStockThreshold: 0 },
  { name: "Jeerakam", tamilName: "ஜீரகம்", tag: "grocery", unit: "kg", qty: 0, globalPrice: 360, openingStock: 0, lowStockThreshold: 0 },
  { name: "Kaada", tamilName: "காட", tag: "meat-fish", unit: "piece", qty: 0, globalPrice: 70, openingStock: 0, lowStockThreshold: 0 },
  { name: "Keera", tamilName: "கீரை", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 120, openingStock: 0, lowStockThreshold: 0 },
  { name: "Malli Ilai", tamilName: "மல்லி இலை", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 100, openingStock: 0, lowStockThreshold: 0 },
  { name: "Malli Leaves", tamilName: "மல்லி இலை", tag: "grocery", unit: "gm", qty: 0, globalPrice: 80, openingStock: 0, lowStockThreshold: 0 },
  { name: "Mustad", tamilName: "கடுகு", tag: "grocery", unit: "kg", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Mutton", tamilName: "மட்டன்", tag: "meat-fish", unit: "kg", qty: 0, globalPrice: 1100, openingStock: 0, lowStockThreshold: 0 },
  { name: "Naattu Koli", tamilName: "நாட்டு கோழி", tag: "meat-fish", unit: "kg", qty: 0, globalPrice: 320, openingStock: 0, lowStockThreshold: 0 },
  { name: "Onion Leaves", tamilName: "ஆனியன் லீவ்ஸ்", tag: "grocery", unit: "kg", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Panneer", tamilName: "பன்னீர்", tag: "grocery", unit: "kg", qty: 0, globalPrice: 500, openingStock: 0, lowStockThreshold: 0 },
  { name: "Puthina Leaves", tamilName: "புதினா இலை", tag: "vegetables", unit: "kg", qty: 0, globalPrice: 100, openingStock: 0, lowStockThreshold: 0 },
  { name: "Raed Chilly Peast", tamilName: "ரேட் சில்லி பேஸ்ட்", tag: "grocery", unit: "ml", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Rampa Leaves", tamilName: "ரம்ப இலை", tag: "grocery", unit: "piece", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Raw Rice", tamilName: "பச்சை அரிசி", tag: "grocery", unit: "kg", qty: 0, globalPrice: 40, openingStock: 0, lowStockThreshold: 0 },
  { name: "Rawa", tamilName: "ரவா", tag: "grocery", unit: "kg", qty: 0, globalPrice: 80, openingStock: 0, lowStockThreshold: 0 },
  { name: "Soda Salt", tamilName: "சோடா சால்ட்", tag: "grocery", unit: "kg", qty: 0, globalPrice: 130, openingStock: 0, lowStockThreshold: 0 },
  { name: "Soya Sause", tamilName: "சோயா சாஸ்", tag: "grocery", unit: "ml", qty: 0, globalPrice: 0, openingStock: 0, lowStockThreshold: 0 },
  { name: "Urugai", tamilName: "ஊறுகாய்", tag: "grocery", unit: "kg", qty: 0, globalPrice: 10, openingStock: 0, lowStockThreshold: 0 },
  { name: "Van Koli", tamilName: "வான் கோழி", tag: "meat-fish", unit: "kg", qty: 0, globalPrice: 600, openingStock: 0, lowStockThreshold: 0 },
  { name: "Veraku", tamilName: "விறகு", tag: "fuel", unit: "kg", qty: 0, globalPrice: 12, openingStock: 0, lowStockThreshold: 0 },
];