/**
 * Auto-generated from the old app (mampally-new.vercel.app) on 2026-09-19.
 * Meals: Saapadu, Biriyani — ingredients matched by English name (case-insensitive) at import time.
 * Do not hand-edit; regenerate via temp script if the old app changes.
 */

import type { IngredientTag } from "./ingredientTags";

export type LegacySeedIngredient = {
  nameEn: string;
  nameTa: string;
  unit: string;
  tag: IngredientTag;
  pricePerUnit: number;
};

export type LegacySeedItem = {
  nameEn: string;
  qtyPer100: number;
};

export type LegacySeedCourse = {
  nameEn: string;
  nameTa: string;
  items: LegacySeedItem[];
};

export type LegacySeedMeal = {
  nameEn: string;
  nameTa: string;
  courses: LegacySeedCourse[];
};

export const LEGACY_INGREDIENTS: LegacySeedIngredient[] = [
  { nameEn: "3 Burner Gas Stove", nameTa: "3 பர்னர் கேஸ் அடுப்பு", unit: "piece", tag: "vessel", pricePerUnit: 650 },
  { nameEn: "Ada", nameTa: "அடை", unit: "kg", tag: "grocery", pricePerUnit: 100 },
  { nameEn: "Apple Ponni Rice", nameTa: "ஆப்பிள் பொன்னி அரிசி", unit: "kg", tag: "grocery", pricePerUnit: 68 },
  { nameEn: "Asafoetida", nameTa: "எல் ஜி காயம்", unit: "kg", tag: "grocery", pricePerUnit: 1500 },
  { nameEn: "Asafoetida Powder", nameTa: "LGகாயம்பொடி", unit: "kg", tag: "grocery", pricePerUnit: 1100 },
  { nameEn: "Aval", nameTa: "அவல்", unit: "kg", tag: "grocery", pricePerUnit: 80 },
  { nameEn: "Banana Fruit", nameTa: "வாழைப் பழம்", unit: "piece", tag: "vegetables", pricePerUnit: 10 },
  { nameEn: "Banana Leaf", nameTa: "வாழ இலை", unit: "piece", tag: "vegetables", pricePerUnit: 5 },
  { nameEn: "Basin", nameTa: "பேசன்", unit: "piece", tag: "vessel", pricePerUnit: 20 },
  { nameEn: "Beans", nameTa: "பீன்ஸ்", unit: "kg", tag: "vegetables", pricePerUnit: 100 },
  { nameEn: "Beetroot", nameTa: "பீட்ரூட்", unit: "kg", tag: "vegetables", pricePerUnit: 60 },
  { nameEn: "Big Onion", nameTa: "பல்லரி", unit: "kg", tag: "vegetables", pricePerUnit: 50 },
  { nameEn: "Bitter Gourd", nameTa: "பாவக்காய்", unit: "kg", tag: "vegetables", pricePerUnit: 80 },
  { nameEn: "Brinjal", nameTa: "கத்திரிக்காய்", unit: "kg", tag: "vegetables", pricePerUnit: 60 },
  { nameEn: "Broad Beans", nameTa: "அவரக்காய்", unit: "kg", tag: "vegetables", pricePerUnit: 60 },
  { nameEn: "Brt Coconut Oil", nameTa: "BRT தேங்காய் எண்ணை", unit: "L", tag: "grocery", pricePerUnit: 300 },
  { nameEn: "Cabbage", nameTa: "முட்டைகோஸ்", unit: "kg", tag: "vegetables", pricePerUnit: 70 },
  { nameEn: "Candy Sugar", nameTa: "சீனி", unit: "kg", tag: "grocery", pricePerUnit: 90 },
  { nameEn: "Canister", nameTa: "கான்பினார்", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Capsicum", nameTa: "கேப்சிகம்", unit: "kg", tag: "vegetables", pricePerUnit: 100 },
  { nameEn: "Cardamom", nameTa: "ஏலக்காய்", unit: "g", tag: "masala-spices", pricePerUnit: 0 },
  { nameEn: "Cauliflower", nameTa: "காலிபிளவர்", unit: "kg", tag: "vegetables", pricePerUnit: 80 },
  { nameEn: "Chair", nameTa: "செயர்", unit: "piece", tag: "vessel", pricePerUnit: 10 },
  { nameEn: "Chakku", nameTa: "சக்கு", unit: "g", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Chicken Masala", nameTa: "சிக்கன் மசாலா", unit: "kg", tag: "masala-spices", pricePerUnit: 480 },
  { nameEn: "Chickpea Dal", nameTa: "கடலை பருப்பு", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Chuku", nameTa: "சுக்கு", unit: "g", tag: "grocery", pricePerUnit: 50 },
  { nameEn: "Cinnamon", nameTa: "பட்டை", unit: "kg", tag: "grocery", pricePerUnit: 1500 },
  { nameEn: "Cloves", nameTa: "கிராம்பு", unit: "kg", tag: "grocery", pricePerUnit: 800 },
  { nameEn: "Coconut", nameTa: "தேங்காய்", unit: "piece", tag: "grocery", pricePerUnit: 45 },
  { nameEn: "Colocasia", nameTa: "சேம்பு கிழங்கு", unit: "kg", tag: "vegetables", pricePerUnit: 120 },
  { nameEn: "Coriander Leaves", nameTa: "மல்லி இலை", unit: "g", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Coriander Powder", nameTa: "மல்லி பொடி", unit: "g", tag: "masala-spices", pricePerUnit: 0 },
  { nameEn: "Cucumber", nameTa: "வெள்ளரிக்காய்", unit: "kg", tag: "vegetables", pricePerUnit: 50 },
  { nameEn: "Cumin", nameTa: "ஜீரகம்", unit: "kg", tag: "grocery", pricePerUnit: 360 },
  { nameEn: "Curry Leaves", nameTa: "கறிவேப்பிலை", unit: "g", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Cylinder", nameTa: "சிலிண்டர்", unit: "kg", tag: "vessel", pricePerUnit: 130 },
  { nameEn: "Drum", nameTa: "டிரம்", unit: "piece", tag: "vessel", pricePerUnit: 50 },
  { nameEn: "Drumstick", nameTa: "முருங்கைக்காய்", unit: "kg", tag: "vegetables", pricePerUnit: 80 },
  { nameEn: "Fenugreek", nameTa: "வெந்தயம்", unit: "g", tag: "masala-spices", pricePerUnit: 0 },
  { nameEn: "Firewood", nameTa: "விரகு", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Fish Maker", nameTa: "மீன்மேக்கர்", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Garlic", nameTa: "பூண்டு", unit: "kg", tag: "grocery", pricePerUnit: 200 },
  { nameEn: "Ginger", nameTa: "இஞ்சி", unit: "kg", tag: "vegetables", pricePerUnit: 200 },
  { nameEn: "Gooseberry", nameTa: "நெல்லிக்காய்", unit: "kg", tag: "vegetables", pricePerUnit: 120 },
  { nameEn: "Green Peas", nameTa: "பச்சை பட்டாணி", unit: "kg", tag: "grocery", pricePerUnit: 100 },
  { nameEn: "Green Pepper (pandi)", nameTa: "பச்சை மிளகு (பாண்டி)", unit: "kg", tag: "vegetables", pricePerUnit: 80 },
  { nameEn: "Grinder", nameTa: "கிரெண்டர்", unit: "piece", tag: "vessel", pricePerUnit: 600 },
  { nameEn: "Ice Cream", nameTa: "ஐஸ்கிரீம்", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Idli Kuttuvam", nameTa: "இட்லி குட்டுவம்", unit: "piece", tag: "vessel", pricePerUnit: 250 },
  { nameEn: "Juck", nameTa: "ஜெக்", unit: "piece", tag: "vessel", pricePerUnit: 20 },
  { nameEn: "Kadavam", nameTa: "கடவம்", unit: "piece", tag: "vessel", pricePerUnit: 250 },
  { nameEn: "Kannappai", nameTa: "கண்ணாப்பை", unit: "piece", tag: "vessel", pricePerUnit: 50 },
  { nameEn: "Karandi", nameTa: "கரண்டி", unit: "piece", tag: "vessel", pricePerUnit: 10 },
  { nameEn: "Karungaali Powder", nameTa: "கருங்காலி பொடி", unit: "g", tag: "masala-spices", pricePerUnit: 0 },
  { nameEn: "Kashmiri Chilli Powder", nameTa: "காஷ்மீரி சில்லி பொடி", unit: "kg", tag: "grocery", pricePerUnit: 300 },
  { nameEn: "Kayam", nameTa: "காயம்", unit: "kg", tag: "grocery", pricePerUnit: 1500 },
  { nameEn: "Kerosene", nameTa: "மண் எண்ணை", unit: "L", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Kundhuponi", nameTa: "குந்துபோணி", unit: "piece", tag: "vessel", pricePerUnit: 25 },
  { nameEn: "Kutai", nameTa: "குட்டை", unit: "piece", tag: "vessel", pricePerUnit: 150 },
  { nameEn: "Ladies Finger", nameTa: "வெண்டைக்காய்", unit: "kg", tag: "vegetables", pricePerUnit: 50 },
  { nameEn: "Ladle", nameTa: "அகப்பை", unit: "piece", tag: "vessel", pricePerUnit: 30 },
  { nameEn: "Large Cast Vessel", nameTa: "பெரிய வார்ப்பு", unit: "piece", tag: "vessel", pricePerUnit: 350 },
  { nameEn: "Large Uruli", nameTa: "பெரிய உருளி", unit: "piece", tag: "vessel", pricePerUnit: 150 },
  { nameEn: "Lemon", nameTa: "எலுமிச்சை", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Matchbox", nameTa: "தீப்பெட்டி", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Matti Fruit", nameTa: "மட்டி பழம்", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Meat", nameTa: "கறி", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Medium Cast Vessel", nameTa: "மீடியம் வார்ப்பு", unit: "piece", tag: "vessel", pricePerUnit: 250 },
  { nameEn: "Milk Maid", nameTa: "மிலக் மேய்டு", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Milk Mavu", nameTa: "மில்க் மாவு", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Milk Powder (Everyday)", nameTa: "பால்பொடி (Everyday)", unit: "g", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Mint Leaves", nameTa: "புதினா இலை", unit: "g", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Mixie", nameTa: "மிக்ஸி", unit: "piece", tag: "vessel", pricePerUnit: 500 },
  { nameEn: "Muthiri Fruit", nameTa: "முத்திரி பழம்", unit: "g", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Mutton Masala", nameTa: "மட்டன் மசாலா", unit: "g", tag: "masala-spices", pricePerUnit: 0 },
  { nameEn: "Narangai", nameTa: "நாரங்காய்", unit: "piece", tag: "vegetables", pricePerUnit: 100 },
  { nameEn: "Nilavaka", nameTa: "நிலவாகா", unit: "piece", tag: "vessel", pricePerUnit: 50 },
  { nameEn: "Palai", nameTa: "பாளை", unit: "piece", tag: "vessel", pricePerUnit: 35 },
  { nameEn: "Pama Oil", nameTa: "பாமா ஆயில்", unit: "L", tag: "grocery", pricePerUnit: 140 },
  { nameEn: "Pame Oil", nameTa: "பமே ஆயில்", unit: "L", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Pandan Leaf", nameTa: "ராம்பா இலை", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Papad", nameTa: "பப்படம்", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Parambu", nameTa: "பரம்பு", unit: "piece", tag: "vessel", pricePerUnit: 150 },
  { nameEn: "Parotta Gas Stove", nameTa: "புரோட்டா கேஸ் அடுப்பு", unit: "piece", tag: "vessel", pricePerUnit: 1000 },
  { nameEn: "Parotta Table", nameTa: "புரோட்டா மேஜை", unit: "piece", tag: "vessel", pricePerUnit: 500 },
  { nameEn: "Perinjeeragam", nameTa: "பெரிஞ்சீரகம்", unit: "g", tag: "masala-spices", pricePerUnit: 0 },
  { nameEn: "Perinjeeragam Powder", nameTa: "பெரிஞ்சீரக பொடி", unit: "g", tag: "masala-spices", pricePerUnit: 0 },
  { nameEn: "Pineapple", nameTa: "பைனாப்பிள்", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Pineapple Color", nameTa: "அன்னாசி பழுப்பு", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Pineapple Essence", nameTa: "பையனாப்பின் எசன்ஸ்", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Plantain", nameTa: "வாழைக்காய்", unit: "kg", tag: "vegetables", pricePerUnit: 80 },
  { nameEn: "Pomegranate", nameTa: "மாதுளம் பழம்", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Potato", nameTa: "உருளை கிழங்கு", unit: "kg", tag: "vegetables", pricePerUnit: 50 },
  { nameEn: "Raw Banana", nameTa: "ஏத்தன்காய்", unit: "piece", tag: "vegetables", pricePerUnit: 10 },
  { nameEn: "Raw Mango", nameTa: "மாங்காய்", unit: "kg", tag: "vegetables", pricePerUnit: 100 },
  { nameEn: "Rice (IVN)", nameTa: "அரிசி (IVN C.O)", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Rice Box", nameTa: "அரி பெட்டி", unit: "piece", tag: "vessel", pricePerUnit: 75 },
  { nameEn: "Rkg Ghee", nameTa: "RKG தெய்", unit: "kg", tag: "grocery", pricePerUnit: 800 },
  { nameEn: "Round yam", nameTa: "சேணை கிழங்கு", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Sabina Powder", nameTa: "சபீனா பொடி", unit: "g", tag: "masala-spices", pricePerUnit: 0 },
  { nameEn: "Sago", nameTa: "சவ்வரிசி", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Salad Cucumber", nameTa: "சலாடு வெள்ளரி", unit: "kg", tag: "vegetables", pricePerUnit: 100 },
  { nameEn: "Salt Granules", nameTa: "உப்பு பரல்", unit: "g", tag: "masala-spices", pricePerUnit: 0 },
  { nameEn: "Salt Powder", nameTa: "உப்பு பொடி", unit: "kg", tag: "masala-spices", pricePerUnit: 13 },
  { nameEn: "Sambar Dal", nameTa: "சாம்பார் பருப்பு", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Sambar Pepper", nameTa: "சாம்பார் மிளகு", unit: "g", tag: "masala-spices", pricePerUnit: 0 },
  { nameEn: "Sambar Powder (Baby)", nameTa: "சாம்பார்பொடி (பேபி)", unit: "g", tag: "masala-spices", pricePerUnit: 0 },
  { nameEn: "Sattuvanam", nameTa: "சட்டுவம்", unit: "piece", tag: "vessel", pricePerUnit: 50 },
  { nameEn: "Sesame Oil", nameTa: "நல்லெண்ணை", unit: "L", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Single Burner Gas Stove", nameTa: "சிங்கிள் பர்னர் கேஸ் அடுப்பு", unit: "piece", tag: "vessel", pricePerUnit: 250 },
  { nameEn: "Sippil", nameTa: "சிப்பில்", unit: "piece", tag: "vessel", pricePerUnit: 20 },
  { nameEn: "Small Dal", nameTa: "சிறு பருப்பு", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Small Karandi", nameTa: "சின்ன கரண்டி", unit: "piece", tag: "vessel", pricePerUnit: 10 },
  { nameEn: "Small Onion", nameTa: "சின்ன உள்ளி", unit: "kg", tag: "grocery", pricePerUnit: 80 },
  { nameEn: "Small Sattuvanam", nameTa: "சிறிய சட்டுவம்", unit: "piece", tag: "vessel", pricePerUnit: 40 },
  { nameEn: "Small Uruli", nameTa: "சின்ன உருளி", unit: "piece", tag: "vessel", pricePerUnit: 150 },
  { nameEn: "Snake Gourd", nameTa: "புடலங்காய்", unit: "kg", tag: "vegetables", pricePerUnit: 65 },
  { nameEn: "Sugar", nameTa: "சர்க்கரை", unit: "kg", tag: "grocery", pricePerUnit: 120 },
  { nameEn: "Sundu", nameTa: "சுண்டு", unit: "g", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Table", nameTa: "மேசை", unit: "piece", tag: "vessel", pricePerUnit: 30 },
  { nameEn: "Tamarind", nameTa: "புளி", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Tea Leaves", nameTa: "தேயிலை", unit: "g", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Thadiyangai", nameTa: "தடியங்காய்", unit: "kg", tag: "vegetables", pricePerUnit: 60 },
  { nameEn: "Thaththolal", nameTa: "தத்தோலால்", unit: "g", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Tomato", nameTa: "தக்காளி", unit: "kg", tag: "vegetables", pricePerUnit: 40 },
  { nameEn: "Tomato peast", nameTa: "டொமட்டோ பேஸ்ட்", unit: "ml", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Towel", nameTa: "டவ்வல்", unit: "piece", tag: "vessel", pricePerUnit: 40 },
  { nameEn: "Tray", nameTa: "டிரே", unit: "piece", tag: "vessel", pricePerUnit: 20 },
  { nameEn: "Turmeric Powder", nameTa: "மஞ்சள் பொடி", unit: "g", tag: "masala-spices", pricePerUnit: 0 },
  { nameEn: "Urad Dal", nameTa: "உருட்டு உழுந்து", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "VVD Oil", nameTa: "V.V.D. என்னை", unit: "L", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Vaalie", nameTa: "வாழி", unit: "piece", tag: "vessel", pricePerUnit: 30 },
  { nameEn: "Vanilla Essence", nameTa: "வெண்ணிலா எசன்ஸ்", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Vathal", nameTa: "வத்தல்", unit: "g", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Vathal Powder", nameTa: "வத்தல் பொடி", unit: "g", tag: "masala-spices", pricePerUnit: 0 },
  { nameEn: "Vattai 10 Kg", nameTa: "வட்டை 10 கிலோ", unit: "piece", tag: "vessel", pricePerUnit: 100 },
  { nameEn: "Vattai 15 Kg", nameTa: "வட்டை 15 கிலோ", unit: "piece", tag: "vessel", pricePerUnit: 100 },
  { nameEn: "Vattai 20 Kg", nameTa: "வட்டை 20 கிலோ", unit: "piece", tag: "vessel", pricePerUnit: 100 },
  { nameEn: "Vattai 30 Kg", nameTa: "வட்டை 30 கிலோ", unit: "piece", tag: "vessel", pricePerUnit: 120 },
  { nameEn: "Vattai 40 Kg", nameTa: "வட்டை 40 கிலோ", unit: "piece", tag: "vessel", pricePerUnit: 150 },
  { nameEn: "Vattai 50 Kg", nameTa: "வட்டை 50 கிலோ", unit: "piece", tag: "vessel", pricePerUnit: 150 },
  { nameEn: "Vazhudhana", nameTa: "வழுதனங்காய்", unit: "kg", tag: "vegetables", pricePerUnit: 60 },
  { nameEn: "Vermicelli", nameTa: "சேமியா", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Viccappa Kuttuvam", nameTa: "வீச்சப்ப குட்டுவம்", unit: "piece", tag: "vessel", pricePerUnit: 500 },
  { nameEn: "Water Bottle", nameTa: "தண்ணீர் பாட்டில்", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Water Cup", nameTa: "தண்ணீர் கப்", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "White Cloth", nameTa: "வெள்ளை முண்டு", unit: "piece", tag: "vessel", pricePerUnit: 100 },
  { nameEn: "Yam", nameTa: "சேனைகிழங்கு", unit: "kg", tag: "vegetables", pricePerUnit: 60 },
  { nameEn: "Ash Pumkin", nameTa: "தடியங்காய்", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Beef", nameTa: "பீப்", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Carrot", nameTa: "கேரட்", unit: "g", tag: "vegetables", pricePerUnit: 100 },
  { nameEn: "Cashew Nut", nameTa: "அண்டி பருப்பு", unit: "kg", tag: "grocery", pricePerUnit: 1000 },
  { nameEn: "Chicken", nameTa: "சிக்கன்", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Chilly Peast", nameTa: "சில்லி பேஸ்ட்", unit: "ml", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Curd", nameTa: "தயிர்", unit: "L", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Egg", nameTa: "முட்டை", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Fish", nameTa: "பிஷ்", unit: "piece", tag: "meat-fish", pricePerUnit: 40 },
  { nameEn: "Gas", nameTa: "காஸ்", unit: "kg", tag: "fuel", pricePerUnit: 175 },
  { nameEn: "Gas Silinder", nameTa: "காஸ் சிலிண்டர்", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Green Chilly", nameTa: "கிறீன் சில்லி", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "India Gate White Sella", nameTa: "இந்தியா கேட் வைட் செல்ல", unit: "kg", tag: "grocery", pricePerUnit: 135 },
  { nameEn: "Jeerakam", nameTa: "ஜீரகம்", unit: "kg", tag: "grocery", pricePerUnit: 360 },
  { nameEn: "Kaada", nameTa: "காட", unit: "piece", tag: "meat-fish", pricePerUnit: 70 },
  { nameEn: "Keera", nameTa: "கீரை", unit: "kg", tag: "vegetables", pricePerUnit: 120 },
  { nameEn: "Malli Ilai", nameTa: "மல்லி இலை", unit: "kg", tag: "vegetables", pricePerUnit: 100 },
  { nameEn: "Malli Leaves", nameTa: "மல்லி இலை", unit: "g", tag: "grocery", pricePerUnit: 80 },
  { nameEn: "Mustad", nameTa: "கடுகு", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Mutton", nameTa: "மட்டன்", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Naattu Koli", nameTa: "நாட்டு கோழி", unit: "kg", tag: "meat-fish", pricePerUnit: 320 },
  { nameEn: "Onion Leaves", nameTa: "ஆனியன் லீவ்ஸ்", unit: "kg", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Panneer", nameTa: "பன்னீர்", unit: "kg", tag: "grocery", pricePerUnit: 500 },
  { nameEn: "Puthina Leaves", nameTa: "புதினா இலை", unit: "kg", tag: "vegetables", pricePerUnit: 100 },
  { nameEn: "Raed Chilly Peast", nameTa: "ரேட் சில்லி பேஸ்ட்", unit: "ml", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Rampa Leaves", nameTa: "ரம்ப இலை", unit: "piece", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Raw Rice", nameTa: "பச்சை அரிசி", unit: "kg", tag: "grocery", pricePerUnit: 40 },
  { nameEn: "Rawa", nameTa: "ரவா", unit: "kg", tag: "grocery", pricePerUnit: 80 },
  { nameEn: "Soda Salt", nameTa: "சோடா சால்ட்", unit: "kg", tag: "grocery", pricePerUnit: 130 },
  { nameEn: "Soya Sause", nameTa: "சோயா சாஸ்", unit: "ml", tag: "grocery", pricePerUnit: 0 },
  { nameEn: "Urugai", nameTa: "ஊறுகாய்", unit: "kg", tag: "grocery", pricePerUnit: 10 },
  { nameEn: "Van Koli", nameTa: "வான் கோழி", unit: "kg", tag: "meat-fish", pricePerUnit: 600 },
  { nameEn: "Veraku", nameTa: "விறகு", unit: "kg", tag: "fuel", pricePerUnit: 12 },
];

export const LEGACY_MEALS: LegacySeedMeal[] = [
  {
    nameEn: "Saapadu",
    nameTa: "சாப்பாடு",
    courses: [
      {
        nameEn: "Urulai Kilangu",
        nameTa: "உருளை கிழங்கு",
        items: [{ nameEn: "Potato", qtyPer100: 3 }, { nameEn: "Coconut", qtyPer100: 3 }, { nameEn: "Big Onion", qtyPer100: 1.5 }, { nameEn: "Brt Coconut Oil", qtyPer100: 0.3 }, { nameEn: "Cinnamon", qtyPer100: 0.02 }],
      },
      {
        nameEn: "Cose Porial",
        nameTa: "கோஸ் பொரியல்",
        items: [{ nameEn: "Cabbage", qtyPer100: 1.5 }],
      },
      { nameEn: "Pachadi", nameTa: "பச்சடி", items: [] },
      { nameEn: "Beetroot Pachadi", nameTa: "பீட்ரூட் பச்சடி", items: [] },
      { nameEn: "Vandakkai Pachadi", nameTa: "வெண்டைக்காய் பச்சடி", items: [] },
      { nameEn: "Pavakkaai  Pachadi", nameTa: "பாவக்காய் பச்சடி", items: [] },
      { nameEn: "சிக்கன் Roast", nameTa: "சிக்கன் ரோஸ்ட்", items: [] },
      { nameEn: "Mankaai Urukai", nameTa: "மாங்காய் ஊறுகாய்", items: [] },
      { nameEn: "Inji Urukai", nameTa: "இஞ்சி ஊறுகாய்", items: [] },
      { nameEn: "‌naarangai Urugai", nameTa: "நாராங்காய் ஊறுகாய்", items: [] },
      { nameEn: "Valakaai Porial", nameTa: "வாழைக்காய் பொரியல்", items: [] },
      { nameEn: "Sambar", nameTa: "சாம்பார்", items: [] },
      { nameEn: "Moru", nameTa: "மொர்", items: [] },
      { nameEn: "Moru Curry", nameTa: "மொர் கறி", items: [] },
      { nameEn: "Vattha Kulambu", nameTa: "வத்த குழம்பு", items: [] },
      { nameEn: "Mutton Curry", nameTa: "மட்டன் கறி", items: [] },
      { nameEn: "Chicken Curry", nameTa: "சிக்கன் கறி", items: [] },
      { nameEn: "Parupu Payazam", nameTa: "பருப்பு பாயாசம்", items: [] },
      { nameEn: "Kadala Parupu Payasam", nameTa: "கடலை பருப்பு பாயசம்", items: [] },
      { nameEn: "Beef Curry", nameTa: "பீப் கறி", items: [] },
      { nameEn: "பீப் Roast", nameTa: "பீப் ரோஸ்ட்", items: [] },
      { nameEn: "Carrot Payasam", nameTa: "கேரட் பாயசம்", items: [] },
      { nameEn: "Pusani Payasam", nameTa: "பூசணி பாயசம்", items: [] },
      { nameEn: "Alwa", nameTa: "அல்வா", items: [] },
      { nameEn: "Ampalapula Payazam", nameTa: "ஆம்பலப்புழ பாயாசம்", items: [] },
      { nameEn: "Semiya Payazam", nameTa: "சேமியா பாயாசம்", items: [] },
      {
        nameEn: "Moru Vathal",
        nameTa: "மொர் வத்தல்",
        items: [{ nameEn: "Ada", qtyPer100: 11 }],
      },
      { nameEn: "Elai", nameTa: "இலை", items: [] },
      { nameEn: "பேப்பர் Roll", nameTa: "பேப்பர் ரோல்", items: [] },
      { nameEn: "Thanir Bottle", nameTa: "தண்ணீ பாட்டில்", items: [] },
      { nameEn: "Thanir Cup", nameTa: "தண்ணீர் கப்", items: [] },
      { nameEn: "F", nameTa: "ப", items: [] },
      { nameEn: "Ff", nameTa: "பிபி", items: [] },
      { nameEn: "Payaa", nameTa: "பாயா", items: [] },
      { nameEn: "Pay", nameTa: "பெ", items: [] },
      { nameEn: "Carrot Kootu", nameTa: "கேரட் கூட்டு", items: [] },
      { nameEn: "Turmeric Milk", nameTa: "தூரமெரிக் மில்க்", items: [] },
      { nameEn: "Adai Payasam", nameTa: "ஆடை பாயச", items: [] },
      { nameEn: "Rice", nameTa: "ரைஸ்", items: [] },
      { nameEn: "Beans Porial", nameTa: "பீன்ஸ் பொரியல்", items: [] },
      {
        nameEn: "Beans Thovayal",
        nameTa: "பீன்ஸ் தொவையல்",
        items: [{ nameEn: "Beans", qtyPer100: 1.5 }],
      },
      {
        nameEn: "Avial",
        nameTa: "அவியல்",
        items: [{ nameEn: "Raw Banana", qtyPer100: 15 }, { nameEn: "Jeerakam", qtyPer100: 0.025 }, { nameEn: "Coconut", qtyPer100: 6 }],
      },
    ],
  },
  {
    nameEn: "Biriyani",
    nameTa: "பிரியாணி",
    courses: [
      {
        nameEn: "Curry",
        nameTa: "குழம்பு",
        items: [{ nameEn: "Ada", qtyPer100: 1000 }],
      },
      {
        nameEn: "Chicken Dum Biriyani",
        nameTa: "சிக்கன் தம் பிரியாணி",
        items: [{ nameEn: "Big Onion", qtyPer100: 6 }, { nameEn: "Cashew Nut", qtyPer100: 0.3 }, { nameEn: "Chicken Masala", qtyPer100: 0.05 }, { nameEn: "Tomato", qtyPer100: 1.5 }],
      },
      { nameEn: "Beef Dum Biriyani", nameTa: "பீப் தம் பிரியாணி", items: [] },
      { nameEn: "Mutton Dum Biriyani", nameTa: "மட்டன் தம் பிரியாணி", items: [] },
      { nameEn: "Neai Soru", nameTa: "நெய் சோறு", items: [] },
      { nameEn: "Veg Kuruma", nameTa: "வெஜ் குருமா", items: [] },
      { nameEn: "Veg Stew", nameTa: "வெஜ் ஸ்ட்வ்", items: [] },
      { nameEn: "Kattarikai Thoku", nameTa: "கத்தரிக்காய் தொக்கு", items: [] },
      { nameEn: "Kadalai Curry", nameTa: "கடலை  கறி", items: [] },
      { nameEn: "Green Peas Curry", nameTa: "கிரீன்  பீஸ் கறி", items: [] },
      { nameEn: "Chicken Stew", nameTa: "சிக்கன் ஸ்ட்வ்", items: [] },
      { nameEn: "Mutton Stew", nameTa: "மட்டன் ஸ்ட்வ்", items: [] },
      { nameEn: "Thair  Ulli", nameTa: "தயிர் உள்ளி", items: [] },
      { nameEn: "Mushroom Biryani", nameTa: "முஸ்ஹரூம் பிரியாணி", items: [] },
      { nameEn: "Appam", nameTa: "அப்பம்", items: [] },
      { nameEn: "Pannir Mutter Masala", nameTa: "பன்னீர் மட்டர் மசாலா", items: [] },
      { nameEn: "Chappathi", nameTa: "சப்பாத்தி", items: [] },
      { nameEn: "Parotta", nameTa: "பரோட்டா", items: [] },
      { nameEn: "Dosa", nameTa: "தோசை", items: [] },
      { nameEn: "Chicken Fry", nameTa: "சிக்கன் பிறை", items: [] },
      { nameEn: "Idli", nameTa: "இட்லி", items: [] },
      { nameEn: "Veachappam", nameTa: "வீச்சப்பம்", items: [] },
      { nameEn: "Cauliflower Fry", nameTa: "காலிப்பிளவர் பிறை", items: [] },
      { nameEn: "Idiapam", nameTa: "இடியாப்பம்", items: [] },
      { nameEn: "Sambar", nameTa: "சாம்பார்", items: [] },
      { nameEn: "Coconut Chutni", nameTa: "தேங்காய் சட்ணி", items: [] },
      { nameEn: "Kara Chutni", nameTa: "காரா சட்ணி", items: [] },
      { nameEn: "Malli  Chutni", nameTa: "மல்லி சட்ணி", items: [] },
      { nameEn: "Putina Chutni", nameTa: "புதினா சட்ணி", items: [] },
      { nameEn: "Rava Kesari", nameTa: "ரவா கேசரி", items: [] },
      { nameEn: "Bread Alwa", nameTa: "பிரட் அல்வா", items: [] },
      { nameEn: "Seamiya Payasam", nameTa: "சேமியா பாயசம்", items: [] },
      { nameEn: "Carrot Alwa", nameTa: "கேரட் அல்வா", items: [] },
      { nameEn: "Elai", nameTa: "இலை", items: [] },
      { nameEn: "Pazham", nameTa: "பழம்", items: [] },
      { nameEn: "Plate", nameTa: "பீலேட்", items: [] },
      { nameEn: "Thanir Cup", nameTa: "தண்ணீர் கப்", items: [] },
      { nameEn: "Payaza Cup", nameTa: "பாயாச கப்", items: [] },
      { nameEn: "Paper Roll", nameTa: "பேப்பர் ரேல்", items: [] },
      { nameEn: "Thanir Bottle", nameTa: "தண்ணீர் பாட்டில்", items: [] },
    ],
  },
];
